---
- hosts: workers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
       
  tasks:

    - name: Ansible Dir Check
      stat:
        path: /home/{{ ansible_user }}/tmp
      register: my_k8s

    - name: "Echo if directory already existe"
      debug:
        msg: "The /tmp Dir is Available"
      when: my_k8s.stat.exists

    - name: "Create directory if it doesn't exist" 
      file:
        path: /home/{{ ansible_user }}/tmp
        state: directory
        mode: 0755
        group: root
        owner: root
      when: my_k8s.stat.exists == false

    - name: Copy join command to worker nodes.
      become: yes
      become_method: sudo
      become_user: root
      copy:
        src: /home/{{ ansible_user }}/tmp/kubernetes_join_command
        dest: /home/{{ ansible_user }}/tmp/kubernetes_join_command
        mode: 0777   

    - name: Join the Worker nodes with the master.
      become: yes
      become_method: sudo
      become_user: root
      command: sh /home/{{ ansible_user }}/tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"


...